#encoding: utf-8

default: &default
  adapter: postgresql
  pool: <%= ENV["DATABASE_POOL"] || 5 %>
  encoding: <%= ENV["DATABASE_ENCODINGT"] || "utf8" %>
  reconnect: true
  timeout: <%= ENV["DATABASE_TIMEOUT"] || 5000 %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  database: <%= ENV["DATABASE_DATABASE"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default

cucumber:
  <<: *test
